services:
  web:
    build: .
    container_name: routinerie_app
    ports:
      - "5001:5001"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
    restart: unless-stopped
    networks:
      - routinerie_network

networks:
  routinerie_network:
    driver: bridge
